#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_ARGS="-d"
NAME=aesdsocket

case "$1" in
  start)
    echo "Starting $NAME..."
    start-stop-daemon -S -n $NAME -a $DAEMON -- $DAEMON_ARGS
    ;;
  stop)
    echo "Stopping $NAME..."
    start-stop-daemon -K -n $NAME
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

